### ISSUE TITLE
Bahasa users not getting the scheduled message

### ISSUE THREAD

**Issue by deemree** [goodbotai/karma#49]
Reported by Dani from their staff training on 28-Oct. Awaiting details.

**Comment by urbanslug** [comment]
Some Indonesian Users are no longer in the "Karma In" group on RapidPro which contains the Indonesian users. Not sure how it happened but will add them back and look out for what could've caused this.

Could be related to unsubscribing from daily messaging because the Former Karma contact group also isn't there.

**Comment by urbanslug** [comment]
I will wait for the run tomorrow before closing this.
